### ISSUE TITLE
Create smaller scale version of network that can run on single processor

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#5] opened 2015-11-10 20:48 UTC
Reuse existing scripts to create a smaller scale version of the network (e.g. with a single glomerulus and reduced numbers of granule cells) that can be run (~100ms) on a single processor.

Will greatly facilitate testing & export of network structure to NML2 (#6)

**Comment by JustasB** [comment] 2015-12-20 18:35
@pgleeson I'm reading your earlier email to Migliore, and I've found the reason why you were getting errors when you changed the Ngloms, grid_dim parameters. It's because the files that are supplied with the model, mitral.dump and c10.dic, store mitral cell and connection data that was generated for the full 127 glom network. In other words, the two files are tightly coupled with the glom/mitral/cell count params. 

If one of those params is changed, then the code reads the files incorrectly, and then eventually errors out. (The suggestion to change "common.nmitral=5" has the same problem.)

I've been able to solve the problem mitral.dump problem by making the code that reads the file to ignore any missing mitral cells, and then keeping the reduced number of mitrals we want.

But the connection file c10.dic is more challenging. The issue is that it stores the connection data for the full-network again, and the code that reads the file assumes the granule/mitral cells for the full network exist and tries to reference non-existing cells. There is also code that does something to the gids, that I'm still trying to understand what it does, that makes it not as simple as checking if the cell gid exists.

Overall, it appears that, in order to allow the model reduction based on a parameter will involve reading the full network files and then adjusting the code to handle the missing cells/connections.

Any tips on alternatives?

**Comment by JustasB** [comment] 2015-12-21 02:20
Ok I modified the code so it handles the missing cells/connections. It's now possible to run a reduced model in NEURON/ folder as "python customsim.py 2 10" which will result in 2 mitral cells with 10 granule cells each. The params specifying more cells than the original model will max out at the orig model cell counts.

Checked in here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/pull/11

**Comment by pgleeson** [comment] 2015-12-21 18:38
@JustasB thanks for your updates. I got your version running successfully on my machine.

Thinking about this though, perhaps it's better, rather than updating/restructuring the original scripts, where settings are distributed among different files, what would you think about creating a new script (CreateOlfactoryBulb.py?) that manages the creation/run of the network model? It could be a cut and paste of the commands from different files (or ideally just importing the methods and running them), but it could be made as configurable (and documented...) as possible, allowing multiple cmd line args [using argparse](https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NEURON_MODIFIED/run_cell.py). It could then be used to generate different instances of the network, apply different inputs, run them and it could potentially manage recording/plotting of activity etc itself. The other advantage would be that the same python script could be used to generate the equivalent network (e.g. 2 mitral cells with 10 granule cells) in NeuroML2 if a -neuroml option is specified.

Possibly a bit more work then originally planned, but ultimately it would lead to a much more usable Olfactory Bulb project and would make it much easier to generate/use the NeuroML2 equivalents on OSB, etc.

**Comment by JustasB** [comment] 2015-12-21 19:28
Sure, I'll make the CreateOlfactoryBulb.py file

**Comment by JustasB** [comment] 2018-02-02 04:27
This has been done here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/pull/25

**Closed as completed by JustasB** 2018-02-02 04:27 UTC
